services:
  database:
    container_name: coffee_delivery_postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coffee_delivery
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d coffee_delivery"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:





